package org.rina.enums;

public enum TypeMeetUp {
    VISITE_GROUPEE,
    APPEL_VISIO,
    APPEL_AUDIO,
    PRESTATION_COIFFURE,
    PRESTATION_MANICURE_PEDICURE,
    PRESTATION_KINESITHERAPEUTE,
    SORTIE_ETABLISSEMENT,
    FLEURISTE,
    AUTRE
}
